im done ;)
kenshinwow1/Shoom pull request #2
Opened 2022-11-15 18:45 UTC by kenshinwow1

2022-11-15 18:46 UTC, kenshinwow1 commented
am i done your task ?

2022-11-16 07:27 UTC, Shemrock3267 requested changes

2022-11-16 07:27 UTC, Shemrock3267 commented on package.json
> +  "author": "I'm",
в полі "author" напиши вкажи свою електронну адресу :)

2022-11-16 07:27 UTC, Shemrock3267 commented on package.json
> +  "description": "Roman2 xD",
Напиши, що це тестовий репозиторій для практики роботи з гітом

2022-11-16 10:29 UTC, Shemrock3267 approved these changes

2022-11-16 10:29 UTC, merged